services:
  postgres:
    image: postgres:17
    container_name: postgres-db
    restart: always
    env_file: ".env"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: imei_api
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis-storage
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  imei-app:
    build: .
    container_name: imei-app
    restart: always
    env_file: ".env"
    environment:
      HOSTNAME: host.docker.internal
      SANIC_DEBUG: False
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data:
